#
# Copyright 2024 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

version: 2.1

orbs:
  android: circleci/android@2.1.2
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-unit-test:
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Check format
          command: make checkformat

      - run:
          name: Check style
          command: make checkstyle

      - run:
          name: Assemble phone release
          command: make assemble-phone-release
      
      - run:
          name: JavaDoc
          command: make javadoc

      - run:
          name: Run unit tests
          command: make unit-test-coverage

      - store_artifacts:
          path: code/edgemedia/build/reports/tests

      - store_test_results:
          path: code/edgemedia/build/test-results/testPhoneDebugUnitTest

      - codecov/upload:          
          file: ./code/edgemedia/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests

  functional-test:
      executor:
        name: android/android-machine
        resource-class: large
        tag: 2024.01.1

      steps:
        - checkout
        
        - android/start-emulator-and-run-tests:
            system-image: system-images;android-29;default;x86
            post-emulator-launch-assemble-command: make assemble-phone
            test-command: make functional-test-coverage

        - store_artifacts:
            path: code/edgemedia/build/reports/androidTests

        - store_test_results:
            path: code/edgemedia/build/outputs/androidTest-results
        
        - codecov/upload:
            file: ./code/edgemedia/build/reports/coverage/androidTest/phone/debug/report.xml            
            flags: functional-tests

workflows:
  version: 2
  aepsdk-edgemedia-ci: 
    jobs:
      - build-and-unit-test
      - functional-test
